---
# tasks/basic_system_settings.yml

- name: Disable unused filesystems
  block:
    - name: Disable mounting of cramfs filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install cramfs /bin/true"
        create: yes
      register: disable_cramfs
      tags: ["cis_1.1.1.1"]

    - name: Disable mounting of freevxfs filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install freevxfs /bin/true"
        create: yes
      register: disable_freevxfs
      tags: ["cis_1.1.1.2"]

    - name: Disable mounting of jffs2 filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install jffs2 /bin/true"
        create: yes
      register: disable_jffs2
      tags: ["cis_1.1.1.3"]

    - name: Disable mounting of hfs filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install hfs /bin/true"
        create: yes
      register: disable_hfs
      tags: ["cis_1.1.1.4"]

    - name: Disable mounting of hfsplus filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install hfsplus /bin/true"
        create: yes
      register: disable_hfsplus
      tags: ["cis_1.1.1.5"]

    - name: Disable mounting of udf filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install udf /bin/true"
        create: yes
      register: disable_udf
      tags: ["cis_1.1.1.6"]

- name: Check if automounting is enabled (cis_1.1.23)
  systemd:
    name: autofs
    state: stopped
    enabled: no
  register: automount_status
  when: is_ubuntu_18
  tags: ["cis_1.1.23"]

- name: Display message if automounting was disabled (cis_1.1.23)
  debug:
    msg: "Automounting was disabled."
  when: is_ubuntu_18
  tags: ["cis_1.1.23"]

- name: Disable USB Storage (cis_1.1.24)
  block:
    - name: Create /etc/modprobe.d/usb_storage.conf
      ansible.builtin.copy:
        dest: /etc/modprobe.d/usb_storage.conf
        content: "install usb-storage /bin/true"
        owner: root
        group: root
        mode: "0644"

    - name: Disable USB Storage in kernel
      ansible.builtin.modprobe:
        name: usb-storage
        state: absent
  when: is_ubuntu_18
  tags: ["cis_1.1.24"]

- name: Check if USB storage module is loaded (cis_1.1.24)
  command: lsmod | grep '^usb_storage '
  register: usb_storage_loaded
  changed_when: false
  failed_when: false
  when: is_ubuntu_18
  tags: ["cis_1.1.24"]

- name: Unload USB storage module if loaded (cis_1.1.24)
  command: rmmod usb_storage
  when: is_ubuntu_18 and usb_storage_loaded.rc == 0
  tags: ["cis_1.1.24"]

- name: Add USB storage module to blacklist (cis_1.1.24)
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "blacklist usb_storage"
    create: yes
    state: present
  when: is_ubuntu_18
  tags: ["cis_1.1.24"]

- name: Update initramfs (cis_1.1.24)
  command: update-initramfs -u
  when: is_ubuntu_18
  tags: ["cis_1.1.24"]

# - name: Install AIDE (cis_1.3.1)
#   apt:
#     name: aide
#     state: present
#   when: is_ubuntu_18
#   tags: ["cis_1.3.1"]

# - name: Initialize AIDE database (cis_1.3.1)
#   command: aideinit
#   args:
#     creates: /var/lib/aide/aide.db.new.gz
#   when: is_ubuntu_18
#   tags: ["cis_1.3.1"]

# - name: Rename AIDE database (cis_1.3.1)
#   command: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
#   args:
#     removes: /var/lib/aide/aide.db.new.gz
#   when: is_ubuntu_18
#   tags: ["cis_1.3.1"]

- name: Check if AIDE CRON job exists (cis_1.3.2)
  stat:
    path: /etc/cron.d/aide
  register: aide_cron_exists
  when: is_ubuntu_18
  tags: ["cis_1.3.2"]

- name: Create AIDE CRON job (cis_1.3.2)
  copy:
    dest: /etc/cron.d/aide
    content: "0 5 * * * root /usr/bin/aide.wrapper --config /etc/aide/aide.conf --check"
    owner: root
    group: root
    mode: "0644"
  when: is_ubuntu_18 and not aide_cron_exists.stat.exists
  tags: ["cis_1.3.2"]

- name: Ensure permissions on bootloader config (cis_1.4.1, cis_1.4.3)
  file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: "0400"
  when: is_ubuntu_18
  tags: ["cis_1.4.1", "cis_1.4.3"]

- name: Ensure authentication required for single user mode (cis_1.4.4)
  lineinfile:
    path: /lib/systemd/system/rescue.service
    line: 'ExecStart=-/bin/sh -c "/sbin/sulogin; /usr/bin/systemctl --fail --no-block default"'
    insertafter: "ExecStart="
    state: present
  when: is_ubuntu_18
  tags: ["cis_1.4.4"]

- name: Check if ASLR is enabled (cis_1.5.2)
  command: sysctl kernel.randomize_va_space
  register: aslr_enabled
  changed_when: false
  when: is_ubuntu_18
  tags: ["cis_1.5.2"]

- name: Enable ASLR (cis_1.5.2)
  sysctl:
    name: kernel.randomize_va_space
    value: "2"
    state: present
    reload: yes
  when: is_ubuntu_18 and aslr_enabled.stdout.find("kernel.randomize_va_space = 2") == -1
  tags: ["cis_1.5.2"]

- name: Ensure ASLR setting persists across reboots (cis_1.5.2)
  lineinfile:
    path: /etc/sysctl.conf
    line: "kernel.randomize_va_space = 2"
    state: present
  when: is_ubuntu_18
  tags: ["cis_1.5.2"]

- name: Ensure message of the day is configured properly (cis_1.7.1)
  lineinfile:
    path: /etc/motd
    line: "Authorized uses only. All activity may be monitored and reported."
    create: yes
    state: present
  when: is_ubuntu_18
  tags: ["cis_1.7.1"]

- name: Ensure permissions on /etc/issue.net are configured (cis_1.7.2)
  ansible.builtin.file:
    path: /etc/issue.net
    owner: root
    group: root
    mode: "0644"
  when: is_ubuntu_18
  tags: ["cis_1.7.2"]

- name: Ensure permissions on /etc/issue are configured (cis_1.7.3)
  ansible.builtin.file:
    path: /etc/issue
    owner: root
    group: root
    mode: "0644"
  when: is_ubuntu_18
  tags: ["cis_1.7.3"]

- name: Ensure permissions on /etc/motd are configured (cis_1.7.4)
  ansible.builtin.file:
    path: /etc/motd
    owner: root
    group: root
    mode: "0644"
  when: is_ubuntu_18
  tags: ["cis_1.7.4"]

- name: Ensure remote login warning banner is configured properly (cis_1.7.5)
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Banner"
    line: "Banner /etc/issue.net"
    state: present
  when: is_ubuntu_18
  tags: ["cis_1.7.5"]

- name: Ensure local login warning banner is configured properly (cis_1.7.6)
  copy:
    dest: /etc/pam.d/login
    content: |
      # Display the message of the day upon successful login.
      session    optional   pam_motd.so  motd=/run/motd.dynamic noupdate
      session    optional   pam_motd.so  motd=/etc/motd
    force: yes
  when: is_ubuntu_18
  tags: ["cis_1.7.6"]

- name: Ensure updates, patches, and additional security software are installed (cis_1.9)
  apt:
    upgrade: safe
    update_cache: yes
  when: is_ubuntu_18
  tags: ["cis_1.9"]

- name: Ensure time synchronization is in use (cis_2.1.1.1)
  block:
    - name: Check if NTP is installed
      package_facts:
        manager: auto
      register: ntp_installed

    - name: Check if chrony is installed
      package_facts:
        manager: auto
      register: chrony_installed

    - name: Ensure NTP or chrony is installed
      assert:
        that:
          - "'ntp' in ntp_installed.ansible_facts.packages or 'chrony' in chrony_installed.ansible_facts.packages"
        fail_msg: "Neither NTP nor chrony is installed. Please install one of them for time synchronization."
  when: is_ubuntu_18
  tags: ["cis_2.1.1.1"]

- name: Ensure systemd-timesyncd is configured (cis_2.1.1.2)
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    regexp: "^NTP="
    line: "NTP=your_ntp_server"
    state: present
  when: is_ubuntu_18
  tags: ["cis_2.1.1.2"]

- name: Ensure chrony is configured (cis_2.1.1.3)
  block:
    - name: Configure chrony
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: "^server"
        line: "server your_ntp_server iburst"
        state: present

    - name: Restart chrony service
      ansible.builtin.systemd:
        name: chrony
        state: restarted
        daemon_reload: yes
  when: is_ubuntu_18 and ('chrony' in ansible_facts.packages)
  tags: ["cis_2.1.1.3"]

- name: Ensure ntp is configured (cis_2.1.1.4)
  block:
    - name: Configure ntp
      lineinfile:
        path: /etc/ntp.conf
        regexp: "^server"
        line: "server your_ntp_server iburst"
        state: present

    - name: Restart ntp service
      ansible.builtin.systemd:
        name: ntp
        state: restarted
        daemon_reload: yes
  when: is_ubuntu_18 and ('ntp' in ansible_facts.packages)
  tags: ["cis_2.1.1.4"]
