---
# tasks/basic_system_settings.yml

- name: Ensure updates, patches, and additional security software are installed
  apt:
    upgrade: safe
    update_cache: yes

- name: Disable unused filesystems
  block:
    - name: Disable mounting of cramfs filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install cramfs /bin/true"
        create: yes
      register: disable_cramfs
      tags: ["cis_1.1.1.1"]

    - name: Disable mounting of freevxfs filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install freevxfs /bin/true"
        create: yes
      register: disable_freevxfs
      tags: ["cis_1.1.1.2"]

    - name: Disable mounting of jffs2 filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install jffs2 /bin/true"
        create: yes
      register: disable_jffs2
      tags: ["cis_1.1.1.3"]

    - name: Disable mounting of hfs filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install hfs /bin/true"
        create: yes
      register: disable_hfs
      tags: ["cis_1.1.1.4"]

    - name: Disable mounting of hfsplus filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install hfsplus /bin/true"
        create: yes
      register: disable_hfsplus
      tags: ["cis_1.1.1.5"]

    - name: Disable mounting of udf filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install udf /bin/true"
        create: yes
      register: disable_udf
      tags: ["cis_1.1.1.6"]

- name: Check if automounting is enabled (cis_1.1.23)
  systemd:
    name: autofs
    state: stopped
    enabled: no
  register: automount_status
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  tags: ["cis_1.1.23"]

- name: Display message if automounting was disabled (cis_1.1.23)
  debug:
    msg: "Automounting was disabled."
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18" and automount_status.changed
  tags: ["cis_1.1.23"]
