---
# tasks/basic_system_settings.yml

- name: Ensure updates, patches, and additional security software are installed
  apt:
    upgrade: safe
    update_cache: yes

- name: Disable unused filesystems
  block:
    - name: Disable mounting of cramfs filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install cramfs /bin/true"
        create: yes
      register: disable_cramfs
      tags: ["cis_1.1.1.1"]

    - name: Disable mounting of freevxfs filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install freevxfs /bin/true"
        create: yes
      register: disable_freevxfs
      tags: ["cis_1.1.1.2"]

    - name: Disable mounting of jffs2 filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install jffs2 /bin/true"
        create: yes
      register: disable_jffs2
      tags: ["cis_1.1.1.3"]

    - name: Disable mounting of hfs filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install hfs /bin/true"
        create: yes
      register: disable_hfs
      tags: ["cis_1.1.1.4"]

    - name: Disable mounting of hfsplus filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install hfsplus /bin/true"
        create: yes
      register: disable_hfsplus
      tags: ["cis_1.1.1.5"]

    - name: Disable mounting of udf filesystem
      lineinfile:
        path: /etc/modprobe.d/cis.conf
        line: "install udf /bin/true"
        create: yes
      register: disable_udf
      tags: ["cis_1.1.1.6"]

- name: Check if automounting is enabled (cis_1.1.23)
  systemd:
    name: autofs
    state: stopped
    enabled: no
  register: automount_status
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  tags: ["cis_1.1.23"]

- name: Display message if automounting was disabled (cis_1.1.23)
  debug:
    msg: "Automounting was disabled."
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18" and automount_status.changed
  tags: ["cis_1.1.23"]

- name: Check if USB storage module is loaded (cis_1.1.24)
  command: lsmod | grep '^usb_storage '
  register: usb_storage_loaded
  changed_when: false
  failed_when: false
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  tags: ["cis_1.1.24"]

- name: Unload USB storage module if loaded (cis_1.1.24)
  command: rmmod usb_storage
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18" and usb_storage_loaded.rc == 0
  tags: ["cis_1.1.24"]

- name: Add USB storage module to blacklist (cis_1.1.24)
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "blacklist usb_storage"
    create: yes
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  tags: ["cis_1.1.24"]

- name: Update initramfs (cis_1.1.24)
  command: update-initramfs -u
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  tags: ["cis_1.1.24"]
- name: Install AIDE (cis_1.3.1)
  apt:
    name: aide
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  tags: ["cis_1.3.1"]

- name: Initialize AIDE database (cis_1.3.1)
  command: aideinit
  args:
    creates: /var/lib/aide/aide.db.new.gz
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  tags: ["cis_1.3.1"]

- name: Rename AIDE database (cis_1.3.1)
  command: mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
  args:
    removes: /var/lib/aide/aide.db.new.gz
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  tags: ["cis_1.3.1"]

- name: Check if AIDE CRON job exists (cis_1.3.2)
  stat:
    path: /etc/cron.d/aide
  register: aide_cron_exists
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18"
  tags: ["cis_1.3.2"]

- name: Create AIDE CRON job (cis_1.3.2)
  copy:
    dest: /etc/cron.d/aide
    content: "0 5 * * * root /usr/bin/aide.wrapper --config /etc/aide/aide.conf --check"
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18" and not aide_cron_exists.stat.exists
  tags: ["cis_1.3.2"]
