- name: Disable IPv6
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  when: is_ubuntu_18
  tags: cis_3.1.1

- name: Disable wireless interfaces
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: "{{ disable_wireless_interfaces | ternary(1, 0) }}"
    state: present
    reload: yes
  when: is_ubuntu_18 and disable_wireless_interfaces
  tags: cis_3.1.2

- name: Disable sending of packet redirects
  command: sysctl -n net.ipv4.conf.all.send_redirects
  register: packet_redirects_status
  changed_when: false
  failed_when: false
  check_mode: no

- name: Disable packet redirect sending
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    sysctl_set: true
    reload: yes
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  tags:
    - cis_3.2.1

- name: Set kernel parameters for packet redirect sending
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item }}"
    state: present
  with_items:
    - "net.ipv4.conf.all.send_redirects = 0"
    - "net.ipv4.conf.default.send_redirects = 0"
  tags:
    - cis_3.2.1

- name: Set active kernel parameters for packet redirect sending
  shell: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv4.conf.all.send_redirects=0"
    - "sysctl -w net.ipv4.conf.default.send_redirects=0"
    - "sysctl -w net.ipv4.route.flush=1"
  tags:
    - cis_3.2.1

- name: Ensure IP forwarding is disabled
  become: true
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ item.file }}"
    state: present
    reload: yes
  with_items:
    - { name: "net.ipv4.ip_forward", value: "0", file: "/etc/sysctl.conf" }
    - {
        name: "net.ipv4.ip_forward",
        value: "0",
        file: "/etc/sysctl.d/99-cis.conf",
      }
  tags: cis_3.2.2

- name: Remove existing IP forwarding configuration
  become: true
  lineinfile:
    path: "{{ item }}"
    regexp: '^net\.ipv4\.ip_forward\s*=\s*1.*'
    line: "# *REMOVED* net.ipv4.ip_forward=1"
    state: present
  with_items:
    - /etc/sysctl.conf
    # - /etc/sysctl.d/*.conf
    # - /usr/lib/sysctl.d/*.conf
    # - /run/sysctl.d/*.conf
  notify: reload sysctl
  tags: cis_3.2.2

- name: Set IP forwarding kernel parameter
  become: true
  sysctl:
    name: net.ipv4.route.flush
    value: "1"
    state: present
  tags: cis_3.2.2

- name: Reload sysctl configuration
  become: true
  meta: flush_handlers
  tags: cis_3.2.2

- name: Disable source routed packets
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    sysctl_set: yes
    reload: yes
  loop:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
    - net.ipv6.conf.all.accept_source_route
    - net.ipv6.conf.default.accept_source_route
  when: is_ubuntu_18

- name: Add sysctl.conf file for source routed packets
  copy:
    src: templates/sysctl.conf.source-routed.j2
    dest: /etc/sysctl.d/99-cis.conf
    owner: root
    group: root
    mode: 0644
  when: is_ubuntu_18
  tags: cis_3.3.1

- name: Disable ICMP redirects
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    sysctl_set: true
    reload: yes
  loop:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  tags:
    - cis_3.3.2

- name: Ensure secure ICMP redirects are not accepted
  sysctl:
    name: "{{ item }}"
    value: "{{ lookup('env', item) }}"
    state: present
    reload: yes
  with_items:
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects
    - net.ipv4.route.flush
  when: is_ubuntu_18
  tags: cis_3.3.3

- name: Ensure suspicious packets are logged
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
  loop:
    - { name: "net.ipv4.conf.all.log_martians", value: 1 }
    - { name: "net.ipv4.conf.default.log_martians", value: 1 }
    - { name: "net.ipv4.route.flush", value: 1 }
  when: is_ubuntu_18

- name: Ensure suspicious packets are logged
  copy:
    dest: /etc/rsyslog.d/99-suspicious.conf
    src: templates/99-suspicious.conf.j2
    mode: "0640"
  notify: restart rsyslog
  tags: cis_3.3.4

- name: Set net.ipv4.icmp_echo_ignore_broadcasts
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
    reload: yes
  tags: cis_3.3.5

- name: Ensure bogus ICMP responses are ignored
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
  tags: cis_3.3.6

- name: Ensure Reverse Path Filtering is enabled
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    state: present
  tags: cis_3.3.7

- name: Ensure TCP SYN Cookies is enabled
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present
    reload: yes
  tags:
    - cis_3.3.8
